### ISSUE TITLE
[END] Status of "INSPIRE UML-to-GeoPackage encoding rule"

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-geopackage-encodings#12]
The "[INSPIRE UML-to-GeoPackage encoding rule](https://github.com/IAAA-Lab/U2G/blob/master/GeoPackage/geopackage-encoding-rule.md)" is mentioned as a normative reference. The reference states clearly that it is a development version, but I am wondering how the END encoding rule can be endorsed when one if its references it is not (yet?) endorsed. We have to discuss how to move forward with that.

**Comment by thorsten-reitz** [comment]
TODO TR remove normative reference and add as literature from which patterns are adopted
