### ISSUE TITLE
[END] terminology: default → constant?

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-geopackage-encodings#14]
According to https://www.collinsdictionary.com/dictionary/english/default:

> 2. adjective [ADJECTIVE noun]
> A default situation is what exists or happens unless someone or something changes it. 
> 
> 3. uncountable noun
> The default is a particular set of instructions which a computer always uses unless the person using the computer gives other instructions. 

So when a value is the default value, that means that that value can still be changed. Would "constant" be a better term?

**Comment by thorsten-reitz** [comment]
The intent of the default value is indeed to be a default value, that can in principle be overridden on a per-feature basis. Thus we would keep the term default for the END case. I will re-check the documentation whether this intent is expressed clearly enough.

**Comment by thorsten-reitz** [comment]
The documentation contained this in the description of the parameters of the Model Transformation rule:

> retainProperty: Optional parameter, if set to true, indicates that while a default property is set, the column is retained in the output schema so that reporters can override the default value for single features. Default is false. This value is not persisted in the table.

I'e made some minor adjustments to the text otherwise to make it clearer that indeed, a default, not a constant is meant.
