### ISSUE TITLE
Finnish topographic database

### ISSUE THREAD

**Issue by reinij** [INSPIRE-MIF/gp-geopackage-encodings#7]
Finnish topographic database is a geopackage, which consists of 120+ feature types (database layers). The size of geopackage is 73 GB (zipped 26 GB). All geometry columns are spatially indexed. 

More information 

Finnish topographic database is downloadable here: https://tiedostopalvelu.maanmittauslaitos.fi/tp/kartta?lang=en

![image](https://user-images.githubusercontent.com/1086184/98333813-396ae280-200a-11eb-86a4-3a9c62c6dd6f.png)

**Comment by heidivanparys** [comment]
Added to the [overview](https://github.com/INSPIRE-MIF/gp-geopackage-encodings/blob/main/examples/overview.md).
