### ISSUE TITLE
Experimental OGC API Features - output as Geopackage

### ISSUE THREAD

**Issue by reinij** [INSPIRE-MIF/gp-geopackage-encodings#8]
NLSFI has also implemented experimental prototype serving topographic database content as Geopackage using OGC API Features.

An example:
http://xxxxx/mtkgml/collections/rakennus/**items?f=gpkg&limit=1000**&crs=http://www.opengis.net/def/crs/EPSG/0/3067

Output: items.gpkg (attached)
[items.zip](https://github.com/INSPIRE-MIF/gp-geopackage-encodings/files/5499679/items.zip)

130 Layers
Size 22 MB
Time: 1.7 seconds
1000 Features

**Comment by heidivanparys** [comment]
Added to the [overview](https://github.com/INSPIRE-MIF/gp-geopackage-encodings/blob/main/examples/overview.md).
